source 'http://rubygems.org'

gem 'rails', '3.2.3'
gem 'haml'
gem 'sass'
gem 'formtastic'
gem 'twitter_oauth'
gem 'oauth2', '~>0.4.1'
gem 'json'
gem 'delayed_job'
gem 'devise'
gem 'typhoeus'
gem 'curb'
gem 'countries'
gem 'mysql2'


group :development, :test do
  gem 'rspec-rails'
  gem 'guard-rspec'
  gem 'mocha'
  gem 'cucumber'
  gem 'cucumber-rails'
  gem 'capybara'
  gem 'spork'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'ruby-debug19'
  gem 'jasmine'
end
