common:
  site_name:  Punchbowl
  facebook_url: 
development:
  url:        http://localhost:3000
  twitter:
    key:      CXgfZm05277FOxb7HBTkUg
    secret:   ky0oGma6zfy4qt8q3Z27JIQpIopbr2aMBhKxbNZ1c    
  facebook: 
    key:      154629021224817
    secret:   48ad712fe340e5e13aaa015bc721a272
  email:
    default:
      to:     aaron@sazboom.com
      from:   punchbowl@mangolanguage.com
  rewards:
    tango:
      start_date: "01/01/2010"
production:
  url:        http://punchbowl.heroku.com
  twitter:
    key:      l1UrVnBEjoaAqgw8zzqCg
    secret:   fxPgyUSyw07WYiRXFia1A68d534MTvB6gtefZFnc
  facebook: 
    key:      121998531187880
    secret:   725abca77adabcae093dc1057136b168
  email:
    default:
      to:     aaron@sazboom.com
      from:   punchbowl@mangolanguage.com
  rewards:
    tango:
      start_date: "01/01/2010"



test:
  url:        http://localhost.com:3000
  twitter:
    key:      CXgfZm05277FOxb7HBTkUg
    secret:   ky0oGma6zfy4qt8q3Z27JIQpIopbr2aMBhKxbNZ1c    
  facebook: 
    key:      154629021224817
    secret:   48ad712fe340e5e13aaa015bc721a272
  email:
    default:
      to:     aaron@sazboom.com
      from:   punchbowl@mangolanguage.com
